-- 1. How many unique customers have placed orders?
SELECT COUNT(DISTINCT cust_id) AS unique_customers
FROM Orders_New;

-- 2. Which customers have placed the highest number of orders?
SELECT TOP 1 WITH TIES
    C.cust_id, 
    C.cust_name, 
    COUNT(O.ord_id) AS total_orders
FROM Customers_New C
JOIN Orders_New O ON C.cust_id = O.cust_id
GROUP BY C.cust_id, C.cust_name
ORDER BY total_orders DESC;

-- 3. What is the total and average purchase value per customer?
SELECT
    C.cust_id,
    C.cust_name,
    SUM(OD.total_price) AS total_purchase_value,
    AVG(OD.total_price) AS average_purchase_value
FROM Customers_New C
JOIN Orders_New O
    ON C.cust_id = O.cust_id
JOIN Order_Details_New OD
    ON O.ord_id = OD.ord_id
GROUP BY C.cust_id, C.cust_name
ORDER BY total_purchase_value DESC;

-- 4. Who are the top 5 customers by total purchase amount?
SELECT TOP 5
    C.cust_id, 
    C.cust_name, 
    SUM(OD.total_price) AS total_purchase_value
FROM Customers_New C
JOIN Orders_New O ON O.cust_id = C.cust_id
JOIN Order_Details_New OD ON OD.ord_id = O.ord_id
GROUP BY C.cust_id, C.cust_name
ORDER BY total_purchase_value DESC;

-- 5. How many products exist in each category?
SELECT  
    C.cat_id, 
    C.cat_name,
    COUNT(*) AS product_count
FROM Products_New P
JOIN Categories_New C ON C.cat_id = P.cat_id
GROUP BY C.cat_id, C.cat_name;

-- 6. What is the average price of products by category?
SELECT 
    AVG(P.price) AS Avg_Prod_cat, 
    C.cat_name
FROM Products_New P
JOIN Categories_New C ON C.cat_id = P.cat_id
GROUP BY C.cat_name;

-- 7. Which products have the highest total sales volume (by quantity)?
SELECT TOP 1
    P.prod_name, 
    SUM(quantity) AS high_sales
FROM Order_Details_New OD
LEFT JOIN Products_New P ON OD.prod_id = P.prod_id
GROUP BY P.prod_name
ORDER BY high_sales DESC;

-- 8. What is the total revenue generated by each product?
SELECT SUM(OD.total_price) AS total_revenue, P.prod_name
FROM Order_Details_New OD
LEFT JOIN Products_New P ON P.prod_id = OD.prod_id
GROUP BY P.prod_name;

-- 9. How do product sales vary by category and supplier?
SELECT
    C.cat_name, S.sup_name,
    SUM(O.total_price) AS total_sales
FROM
    Order_Details_New O
JOIN Products_New P ON O.prod_id = P.prod_id
JOIN Categories_New C ON P.cat_id = C.cat_id
JOIN Supplier_New S ON P.sup_id = S.sup_id
GROUP BY
    C.cat_name, S.sup_name
ORDER BY
    C.cat_name, total_sales DESC;

-- 10. How many orders have been placed in total?
SELECT COUNT(*) AS total_orders FROM Orders_New;

-- 11. What is the average value per order?
SELECT 
    SUM(total_price) / COUNT(DISTINCT ord_id) AS Avg_Order_Value
FROM
    Order_Details_New;

-- 12. On which dates were the most orders placed?
SELECT TOP 1
    order_date,
    COUNT(ord_id) AS order_count
FROM Orders_New
GROUP BY order_date
ORDER BY order_count DESC;

-- 13. What are the monthly trends in order volume and revenue?
SELECT
    FORMAT(O.order_date, 'MMMM') AS order_month,
    COUNT(DISTINCT O.ord_id) AS order_volume,
    SUM(OD.total_price) AS total_revenue
FROM
    Orders_New O
JOIN Order_Details_New OD ON O.ord_id = OD.ord_id
GROUP BY FORMAT(O.order_date, 'MMMM')
ORDER BY FORMAT(O.order_date, 'MMMM');

-- 14. How do order patterns vary across weekdays and weekends?
SELECT 
    DATENAME(WEEKDAY, order_date) AS weekday,
    DATENAME(MONTH, order_date) AS month,
    COUNT(ord_id) AS total_orders
FROM 
    Orders_New
GROUP BY DATENAME(WEEKDAY, order_date), DATENAME(MONTH, order_date)
ORDER BY weekday,month;

-- 15. How many suppliers are there in the database?
SELECT COUNT(*) FROM Supplier_New;

-- 16. Which supplier provides the most products?
SELECT TOP 1
    S.sup_id,
    S.sup_name,
    COUNT(*) AS product_count
FROM Products_New P
JOIN Supplier_New S ON S.sup_id = P.sup_id
GROUP BY S.sup_id, S.sup_name
ORDER BY product_count DESC;

-- 17. What is the average price of products from each supplier?
SELECT
    S.sup_id,
    S.sup_name,
    AVG(P.price) AS Average_Price_Product
FROM Products_New P
JOIN Supplier_New S ON S.sup_id = P.sup_id
GROUP BY S.sup_id, S.sup_name;

-- 18. Which suppliers contribute the most to total product sales (by revenue) ?
SELECT TOP 1
    S.sup_id,
    S.sup_name,
    SUM(OD.total_price) AS Total_Revenue
FROM Products_New P
JOIN Supplier_New S ON S.sup_id = P.sup_id
JOIN Order_Details_New OD ON P.prod_id = OD.prod_id
GROUP BY S.sup_id, S.sup_name
ORDER BY Total_Revenue DESC;

-- 19. How many employees have processed orders?
SELECT COUNT(DISTINCT emp_id) AS Count_Distnct_EmployeeID FROM Orders_New;

-- 20. Which employees have handled the most orders?
SELECT TOP 1
   E.emp_id,
   E.emp_name,
   COUNT(O.ord_id) AS total_number_of_orders 
FROM Employees_New E
JOIN Orders_New O ON E.emp_id = O.emp_id
GROUP BY E.emp_id, E.emp_name
ORDER BY total_number_of_orders DESC;

-- 21. What is the total sales value processed by each employee?
SELECT
    E.emp_id,
    E.emp_name,
    SUM(OD.total_price) AS Total_Sales
FROM Employees_New E
JOIN Orders_New O ON O.emp_id = E.emp_id
JOIN Order_Details_New OD ON O.ord_id = OD.ord_id
GROUP BY E.emp_id,E.emp_name;

-- 22. What is the average order value handled per employee?
SELECT 
    E.emp_id,
    E.emp_name,
    SUM(OD.total_price) / COUNT(DISTINCT O.ord_id) AS Avg_Order_Value
FROM Employees_New E
JOIN Orders_New O ON O.emp_id = E.emp_id
JOIN Order_Details_New OD ON O.ord_id = OD.ord_id
GROUP BY E.emp_id,E.emp_name
ORDER BY Avg_Order_Value DESC;

-- 23. What is the relationship between quantity ordered and total price?
SELECT 
    quantity,
    AVG(total_price) AS Avg_Total_Price,
    COUNT(*) AS Order_Count
FROM Order_Details_New OD
GROUP BY Quantity
ORDER BY Quantity;

-- 24. What is the average quantity ordered per product?
SELECT 
    P.prod_id,
    P.prod_name,
    AVG(OD.quantity)AS Average_Order_Quantity,
    COUNT(OD.ord_id) AS Total_Orders
 FROM Order_Details_New OD
 JOIN Products_New P ON  OD.prod_id = P.prod_id 
 GROUP BY P.prod_id, P.prod_name
 ORDER BY Average_Order_Quantity DESC;

 -- 25. How does the unit price vary across products and orders?
 SELECT 
     P.prod_id,
     P.prod_name,
     OD.each_price AS Unit_Price,
     COUNT(OD.ord_id) AS Times_Ordered
 FROM Products_New P
 JOIN Order_Details_New OD ON P.prod_id = OD.prod_id
 GROUP BY P.prod_id, P.prod_name, OD.each_price
 ORDER BY P.prod_id, OD.each_price;

