-- 1. How many unique customers have placed orders?
SELECT COUNT(DISTINCT cust_id) AS unique_customers
FROM Orders_New;

-- 2. Which customers have placed the highest number of orders?
SELECT TOP 1 WITH TIES
    C.cust_id, 
    C.cust_name, 
    COUNT(O.ord_id) AS total_orders
FROM Customers_New C
JOIN Orders_New O ON C.cust_id = O.cust_id
GROUP BY C.cust_id, C.cust_name
ORDER BY total_orders DESC;

-- 3. What is the total and average purchase value per customer?
SELECT
    C.cust_id,
    C.cust_name,
    SUM(OD.total_price) AS total_purchase_value,
    AVG(OD.total_price) AS average_purchase_value
FROM Customers_New C
JOIN Orders_New O
    ON C.cust_id = O.cust_id
JOIN Order_Details_New OD
    ON O.ord_id = OD.ord_id
GROUP BY C.cust_id, C.cust_name
ORDER BY total_purchase_value DESC;

-- 4. Who are the top 5 customers by total purchase amount?
SELECT TOP 5
    C.cust_id, 
    C.cust_name, 
    SUM(OD.total_price) AS total_purchase_value
FROM Customers_New C
JOIN Orders_New O ON O.cust_id = C.cust_id
JOIN Order_Details_New OD ON OD.ord_id = O.ord_id
GROUP BY C.cust_id, C.cust_name
ORDER BY total_purchase_value DESC;

-- 5. What is the average price of products by category?
SELECT 
    AVG(P.price) AS Avg_Prod_cat, 
    C.cat_name
FROM Products_New P
JOIN Categories_New C ON C.cat_id = P.cat_id
GROUP BY C.cat_name;

-- 6. Which products have the highest total sales volume (by quantity)?
SELECT TOP 1
    P.prod_name, 
    SUM(quantity) AS high_sales
FROM Order_Details_New OD
LEFT JOIN Products_New P ON OD.prod_id = P.prod_id
GROUP BY P.prod_name
ORDER BY high_sales DESC;

-- 7. What is the total revenue generated by each product?
SELECT SUM(OD.total_price) AS total_revenue, P.prod_name
FROM Order_Details_New OD
LEFT JOIN Products_New P ON P.prod_id = OD.prod_id
GROUP BY P.prod_name;

-- 8. How do product sales vary by category and supplier?
SELECT
    C.cat_name, S.sup_name,
    SUM(O.total_price) AS total_sales
FROM
    Order_Details_New O
JOIN Products_New P ON O.prod_id = P.prod_id
JOIN Categories_New C ON P.cat_id = C.cat_id
JOIN Supplier_New S ON P.sup_id = S.sup_id
GROUP BY
    C.cat_name, S.sup_name
ORDER BY
    C.cat_name, total_sales DESC;

-- 9. What is the average value per order?
SELECT 
    SUM(total_price) / COUNT(DISTINCT ord_id) AS Avg_Order_Value
FROM
    Order_Details_New;

-- 10. What are the monthly trends in order volume and revenue?
SELECT
    FORMAT(O.order_date, 'MMMM') AS order_month,
    COUNT(DISTINCT O.ord_id) AS order_volume,
    SUM(OD.total_price) AS total_revenue
FROM
    Orders_New O
JOIN Order_Details_New OD ON O.ord_id = OD.ord_id
GROUP BY FORMAT(O.order_date, 'MMMM')
ORDER BY FORMAT(O.order_date, 'MMMM');

-- 11. Which supplier provides the most products?
SELECT TOP 1
    S.sup_id,
    S.sup_name,
    COUNT(*) AS product_count
FROM Products_New P
JOIN Supplier_New S ON S.sup_id = P.sup_id
GROUP BY S.sup_id, S.sup_name
ORDER BY product_count DESC;

-- 12. What is the average price of products from each supplier?
SELECT
    S.sup_id,
    S.sup_name,
    AVG(P.price) AS Average_Price_Product
FROM Products_New P
JOIN Supplier_New S ON S.sup_id = P.sup_id
GROUP BY S.sup_id, S.sup_name;

-- 13. Which suppliers contribute the most to total product sales (by revenue) ?
SELECT TOP 1
    S.sup_id,
    S.sup_name,
    SUM(OD.total_price) AS Total_Revenue
FROM Products_New P
JOIN Supplier_New S ON S.sup_id = P.sup_id
JOIN Order_Details_New OD ON P.prod_id = OD.prod_id
GROUP BY S.sup_id, S.sup_name
ORDER BY Total_Revenue DESC;

-- 14. Which employees have handled the most orders?
SELECT TOP 1
   E.emp_id,
   E.emp_name,
   COUNT(O.ord_id) AS total_number_of_orders 
FROM Employees_New E
JOIN Orders_New O ON E.emp_id = O.emp_id
GROUP BY E.emp_id, E.emp_name
ORDER BY total_number_of_orders DESC;

-- 15. What is the total sales value processed by each employee?
SELECT
    E.emp_id,
    E.emp_name,
    SUM(OD.total_price) AS Total_Sales
FROM Employees_New E
JOIN Orders_New O ON O.emp_id = E.emp_id
JOIN Order_Details_New OD ON O.ord_id = OD.ord_id
GROUP BY E.emp_id,E.emp_name;

-- 16. What is the average order value handled per employee?
SELECT 
    E.emp_id,
    E.emp_name,
    SUM(OD.total_price) / COUNT(DISTINCT O.ord_id) AS Avg_Order_Value
FROM Employees_New E
JOIN Orders_New O ON O.emp_id = E.emp_id
JOIN Order_Details_New OD ON O.ord_id = OD.ord_id
GROUP BY E.emp_id,E.emp_name
ORDER BY Avg_Order_Value DESC;

-- 17. Who are our High-Value Customers and how much revenue do they contribute?
WITH CustomerRevenue AS (
    SELECT 
        C.cust_name,
        COUNT(DISTINCT O.ord_id) AS total_orders,
        SUM(OD.total_price) AS total_spend,
        AVG(OD.total_price) AS avg_order_value,
        ROUND(SUM(OD.total_price) * 100.0 / SUM(SUM(OD.total_price)) OVER(), 2) AS revenue_contribution_pct
    FROM Customers_New C
    JOIN Orders_New O ON C.cust_id = O.cust_id
    JOIN Order_Details_New OD ON O.ord_id = OD.ord_id
    GROUP BY C.cust_name
)
SELECT * FROM CustomerRevenue 
ORDER BY total_spend DESC;


-- 18. What is the Month-over-Month (MoM) growth in revenue and number of orders?
WITH MonthlyRevenue AS (
    SELECT 
        FORMAT(O.order_date, 'yyyy-MM') AS month_year,
        SUM(OD.total_price) AS revenue,
        COUNT(DISTINCT O.ord_id) AS order_count
    FROM Orders_New O
    JOIN Order_Details_New od ON O.ord_id = OD.ord_id
    GROUP BY FORMAT(O.order_date, 'yyyy-MM')
)
SELECT 
    month_year, 
    revenue, 
    order_count,
    LAG(revenue) OVER (ORDER BY month_year) AS prev_month_revenue,
    ROUND((revenue - LAG(revenue) OVER (ORDER BY month_year)) * 100.0 / 
          NULLIF(LAG(revenue) OVER (ORDER BY month_year), 0), 2) AS mom_growth_pct
FROM MonthlyRevenue
ORDER BY month_year;


-- 19. How do individual products perform within their respective categories?
WITH ProductSales AS (
    SELECT 
        CAT.cat_name,
        P.prod_name,
        SUM(OD.quantity) AS total_quantity_sold,
        SUM(OD.total_price) AS total_revenue,
        RANK() OVER (PARTITION BY cat.cat_name ORDER BY SUM(OD.total_price) DESC) AS rank_in_category
    FROM Order_Details_New OD
    JOIN Products_New P ON OD.prod_id = P.prod_id
    JOIN Categories_New CAT ON P.cat_id = CAT.cat_id
    JOIN Orders_New O ON OD.ord_id = O.ord_id
    GROUP BY CAT.cat_name, P.prod_name
)
SELECT * FROM ProductSales 
ORDER BY cat_name, rank_in_category;


-- 20. Which employees are the best performers based on revenue generated?
SELECT 
    E.emp_name,
    COUNT(DISTINCT O.ord_id) AS orders_processed,
    SUM(OD.total_price) AS total_revenue,
    ROUND(SUM(OD.total_price) / COUNT(DISTINCT O.ord_id), 2) AS avg_order_value,
    RANK() OVER (ORDER BY SUM(OD.total_price) DESC) AS performance_rank
FROM Employees_New E
JOIN Orders_New o ON E.emp_id = O.emp_id
JOIN Order_Details_New OD ON O.ord_id = OD.ord_id
GROUP BY E.emp_name
ORDER BY total_revenue DESC;


-- 21. Which suppliers are contributing the most revenue to the business?
SELECT 
    S.sup_name,
    COUNT(DISTINCT P.prod_id) AS products_supplied,
    SUM(OD.total_price) AS total_revenue_generated,
    ROUND(SUM(OD.total_price) / COUNT(DISTINCT P.prod_id), 2) AS revenue_per_product,
    RANK() OVER (ORDER BY SUM(OD.total_price) DESC) AS supplier_rank
FROM Supplier_New S
JOIN Products_New P ON S.sup_id = P.sup_id
JOIN Order_Details_New OD ON P.prod_id = OD.prod_id
GROUP BY S.sup_name
ORDER BY total_revenue_generated DESC;


-- 22. How does sales performance differ between weekdays and weekends?
SELECT 
    DATENAME(WEEKDAY, O.order_date) AS day_name,
    COUNT(DISTINCT O.ord_id) AS total_orders,
    SUM(OD.total_price) AS total_revenue,
    ROUND(AVG(OD.total_price), 2) AS avg_order_value,
    CASE WHEN DATENAME(WEEKDAY, O.order_date) IN ('Saturday','Sunday') 
         THEN 'Weekend' ELSE 'Weekday' END AS day_type
FROM Orders_New O
JOIN Order_Details_New OD ON O.ord_id = OD.ord_id
GROUP BY DATENAME(WEEKDAY, O.order_date)
ORDER BY total_revenue DESC;


-- 23. What is the revenue contribution percentage of each product category?
SELECT 
    CAT.cat_name,
    SUM(OD.total_price) AS category_revenue,
    ROUND(SUM(OD.total_price) * 100.0 / SUM(SUM(OD.total_price)) OVER(), 2) AS revenue_share_percentage
FROM Categories_New CAT
JOIN Products_New P ON cat.cat_id = P.cat_id
JOIN Order_Details_New od ON P.prod_id = OD.prod_id
GROUP BY CAT.cat_name
ORDER BY category_revenue DESC;


-- 24. What are the top 5 best-selling products by quantity and revenue?
SELECT TOP 5
    P.prod_name,
    CAT.cat_name,
    SUM(OD.quantity) AS total_quantity_sold,
    SUM(OD.total_price) AS total_revenue,
    ROUND(SUM(OD.total_price) * 100.0 / SUM(SUM(OD.total_price)) OVER(), 2) AS revenue_percentage
FROM Order_Details_New OD
JOIN Products_New P ON OD.prod_id = P.prod_id
JOIN Categories_New CAT ON P.cat_id = CAT.cat_id
GROUP BY P.prod_name, CAT.cat_name
ORDER BY total_revenue DESC;